from __future__ import annotations

from enum import StrEnum


class RuntimeMode(StrEnum):
    MONITOR_ONLY = "monitor_only"
    SIMULATION = "simulation"
    LIVE = "live"


class TargetChain(StrEnum):
    MANTLE_SEPOLIA = "mantle_sepolia"
    MANTLE_MAINNET = "mantle_mainnet"


class SystemStatusCode(StrEnum):
    LIVE = "LIVE"
    SIMULATION_ONLY = "SIMULATION_ONLY"
    DEGRADED = "DEGRADED"
    PAUSED = "PAUSED"
    EMERGENCY_PAUSED = "EMERGENCY_PAUSED"
    MAINTENANCE = "MAINTENANCE"


class DataStatusCode(StrEnum):
    DATA_FRESH = "DATA_FRESH"
    DATA_STALE = "DATA_STALE"
    DATA_MISSING = "DATA_MISSING"
    DATA_PARTIAL = "DATA_PARTIAL"
    ORACLE_FRESH = "ORACLE_FRESH"
    ORACLE_STALE = "ORACLE_STALE"
    QUOTE_FRESH = "QUOTE_FRESH"
    QUOTE_STALE = "QUOTE_STALE"
    LIQUIDITY_UNKNOWN = "LIQUIDITY_UNKNOWN"


class RiskStatusCode(StrEnum):
    RISK_NORMAL = "RISK_NORMAL"
    RISK_CAUTION = "RISK_CAUTION"
    RISK_REBALANCE_ONLY = "RISK_REBALANCE_ONLY"
    RISK_REDUCE_ONLY = "RISK_REDUCE_ONLY"
    RISK_PAUSE_REQUIRED = "RISK_PAUSE_REQUIRED"
    RISK_VETO = "RISK_VETO"


class ProposalStatusCode(StrEnum):
    PROPOSAL_DRAFT = "PROPOSAL_DRAFT"
    PROPOSAL_RISK_CHECKING = "PROPOSAL_RISK_CHECKING"
    PROPOSAL_RISK_APPROVED = "PROPOSAL_RISK_APPROVED"
    PROPOSAL_RISK_REJECTED = "PROPOSAL_RISK_REJECTED"
    PROPOSAL_PENDING_APPROVAL = "PROPOSAL_PENDING_APPROVAL"
    PROPOSAL_APPROVED = "PROPOSAL_APPROVED"
    PROPOSAL_REJECTED = "PROPOSAL_REJECTED"
    PROPOSAL_EXPIRED = "PROPOSAL_EXPIRED"
    PROPOSAL_EXECUTING = "PROPOSAL_EXECUTING"
    PROPOSAL_EXECUTED = "PROPOSAL_EXECUTED"
    PROPOSAL_FAILED = "PROPOSAL_FAILED"
    PROPOSAL_EXECUTION_FAILED_RETRYABLE = "PROPOSAL_EXECUTION_FAILED_RETRYABLE"
    PROPOSAL_CANCELLED = "PROPOSAL_CANCELLED"


class ExecutionStatusCode(StrEnum):
    EXECUTION_READY = "EXECUTION_READY"
    EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
    EXECUTION_SUBMITTED = "EXECUTION_SUBMITTED"
    EXECUTION_PENDING = "EXECUTION_PENDING"
    EXECUTION_CONFIRMED = "EXECUTION_CONFIRMED"
    EXECUTION_REVERTED = "EXECUTION_REVERTED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_SKIPPED = "EXECUTION_SKIPPED"
    EXECUTION_SIMULATED = "EXECUTION_SIMULATED"


class ExecutionTrigger(StrEnum):
    AI_CREATE = "ai_create"
    HUMAN_APPROVAL = "human_approval"
    MANUAL_EXECUTE = "manual_execute"
    RETRY = "retry"


class ExecutionEventType(StrEnum):
    PROPOSAL_APPROVED = "PROPOSAL_APPROVED"
    AUTO_EXECUTION_SKIPPED = "AUTO_EXECUTION_SKIPPED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_SUBMITTED = "EXECUTION_SUBMITTED"
    EXECUTION_CONFIRMED = "EXECUTION_CONFIRMED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
    EXECUTION_RETRIED = "EXECUTION_RETRIED"


class AlertSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    RESOLVED = "RESOLVED"
