FROM node:20-alpine AS build

WORKDIR /workspace/frontend

COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps

COPY frontend/ ./
RUN npm run build

FROM node:20-alpine

WORKDIR /workspace/frontend

COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps --only=production

COPY --from=build /workspace/frontend/dist ./dist

EXPOSE 8080

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "8080"]
